FROM public.ecr.aws/h6i3a8b9/mastodon:v4.2.10

# Copy your modified rack_attack.rb file to the correct location
COPY rack_attack.rb /opt/mastodon/config/initializers/rack_attack.rb

# If you need to make any other customizations, do them here
